services:
  frontend:
    build:
      context: ./frontend  # adjust if your frontend folder has another name
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["npm", "start"]
